// rdotswift.js

module.exports = rdotswift;

var rtojson = require("./rdotjson");
var CLASS = "class";
var IF = "if";

/**
 * generates Swift source code from resource XML
 *
 * @param xml {String|Buffer|Stream}
 * @param [options] {Object}
 * @param callback {Function} function(err, swift) {...}
 */

function rdotswift(xml, options, callback) {
  if (options instanceof Function && callback == null) {
    callback = options;
    options = null;
  }

  if (!options) options = {};

  return rtojson(xml, options, then);

  function then(err, R) {
    if (err) {
      if (callback) return callback(err);
      throw err;
    }

    var out = [];

    if (options.header !== false) {
      out.push("// Generated by rdotswift <https://github.com/kawanet/rdotswift>");
      out.push("");
      out.push("import UIKit");
      out.push("");
    }

    if (options[IF]) {
      out.push("#if " + options[IF]);
      out.push("");
    }

    if (options[CLASS]) {
      out.push("final class R {");
      ["bool", "color", "dimen", "string"].map(function(type, idx) {
        if (idx) out.push("");
        out.push("    final class " + type + " {");
        out.push("    }");
      });
      out.push("}");
      out.push("");
    }

    if (options.source) {
      out.push("// " + options.source);
      out.push("");
    }

    out = out.concat(bool(R.bool));
    out = out.concat(color(R.color));
    out = out.concat(dimen(R.dimen));
    out = out.concat(string(R.string));

    if (options[IF]) {
      out.push("#endif");
      out.push("");
    }

    var swift = out.join("\n");
    if (callback) return callback(null, swift);
  }
}

function string(src) {
  var rows = [];
  for (var key in src) {
    var val = src[key];
    rows.push(comment(val));
    val = JSON.stringify(val + "").replace(/\\\\/g, "\\");
    var row = "    static let " + key + " = " + val;
    rows.push(row);
  }
  return extension("string", rows);
}

function color(src) {
  var rows = [];
  for (var key in src) {
    var val = src[key];
    if (!val) return;
    if (!val.match(/^#\w+$/)) return;
    var rgb = parseInt(val.substr(1), 16);
    var blue = rgb & 0xFF;
    rgb >>= 8;
    var green = rgb & 0xFF;
    rgb >>= 8;
    var red = rgb & 0xFF;
    rows.push(comment(val));
    var row = "    static let " + key + " = " +
      "UIColor(red: " + c(red) + ", green: " + c(green) + ", blue:" + c(blue) + ", alpha: 1)";
    rows.push(row);
  }
  return extension("color", rows);

  function c(val) {
    return Math.round(val / 255 * 1000) / 1000;
  }
}

function dimen(src) {
  var rows = [];
  for (var key in src) {
    var val = src[key];
    if (!val) return;
    rows.push(comment(val));
    var row = "    static let " + key + ": CGFloat = " + parseInt(val);
    rows.push(row);
  }
  return extension("dimen", rows);
}

function bool(src) {
  var rows = [];
  for (var key in src) {
    var val = src[key];
    rows.push(comment(val));
    var row = "    static let " + key + " = " + val;
    rows.push(row);
  }
  return extension("bool", rows);
}

function extension(type, rows) {
  if (rows.length) {
    rows.unshift("extension R." + type + " {");
    rows.push("}");
    rows.push("");
  }
  return rows;
}

function comment(val) {
  if (val === "") val = "(empty)";
  if ("string" === typeof val) {
    val = val.replace(/\*\//g, "*\\/");
    val = val.replace(/\n/g, "\\n");
  }
  return "    /** " + val + " */";
}