//  R.swift
//
//  Generated by rdotswift <https://github.com/kawanet/rdotswift>

import Foundation

final class R {
    final class bool {
    }

    final class color {
    }

    final class dimen {
    }

    final class string {
    }
}
